---
- name: install yum package prerequisite - {{ package_id }}
  ansible.builtin.package:
    name: "{{ package_yum_prerequisite }}"
    state: present
  when: ansible_facts['os_family']|lower == 'redhat'

- name: install apt package prerequisite - {{ package_id }}
  ansible.builtin.package:
    name: "{{ package_apt_prerequisite }}"
    state: present
  when: ansible_facts['os_family']|lower == 'debian'

- name: add key and repository using dnf - {{ package_id }}
  import_tasks: dnf.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: add key and repository using apt - {{ package_id }}
  import_tasks: apt.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: install package - {{ package_id }}
  ansible.builtin.package:
    name: "{{ package_name }}"
    state: present
