name: Publish collection to Galaxy
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
          src_path: pretsa/automate