name: Publish collection to Galaxy
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arillso/action.ansible.collection@v1.3.0
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
          collection_dir: ./pretsa/automate
